# Generated by Django 4.0.5 on 2022-07-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Berichts',
            new_name='Bericht',
        ),
        migrations.AlterModelOptions(
            name='bericht',
            options={'verbose_name_plural': 'Berichten'},
        ),
    ]
